-- Repeatable customer-visible shipments for Final Sample rounds and bulk orders.

create table public.fc_order_shipment (
  id bigint generated by default as identity primary key,
  order_id bigint not null,
  customer_id bigint not null,
  shipment_type text not null,
  round_number integer,
  sequence_number integer not null default 1,
  quantity integer,
  carrier text,
  tracking_number text,
  shipped_at timestamptz,
  delivered_at timestamptz,
  sample_approval_status text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint fc_order_shipment_order_customer_fkey
    foreign key (order_id, customer_id)
    references public."order" (id, customer_id)
    on delete cascade,
  constraint fc_order_shipment_customer_id_fkey
    foreign key (customer_id)
    references public.customer (id)
    on delete cascade,
  constraint fc_order_shipment_type_check
    check (shipment_type = any (array['final_sample', 'bulk_order']::text[])),
  constraint fc_order_shipment_round_check
    check (
      (
        shipment_type = 'final_sample'
        and round_number is not null
        and round_number >= 1
      )
      or (
        shipment_type = 'bulk_order'
        and round_number is null
      )
    ),
  constraint fc_order_shipment_sequence_check
    check (sequence_number >= 1),
  constraint fc_order_shipment_quantity_check
    check (quantity is null or quantity > 0),
  constraint fc_order_shipment_carrier_check
    check (carrier is null or length(trim(carrier)) > 0),
  constraint fc_order_shipment_tracking_number_check
    check (
      tracking_number is null
      or (
        length(trim(tracking_number)) > 0
        and shipped_at is not null
      )
    ),
  constraint fc_order_shipment_approval_check
    check (
      (
        shipment_type = 'final_sample'
        and (
          sample_approval_status is null
          or sample_approval_status = any (
            array[
              'awaiting_review',
              'approved',
              'revision_requested'
            ]::text[]
          )
        )
      )
      or (
        shipment_type = 'bulk_order'
        and sample_approval_status is null
      )
    ),
  constraint fc_order_shipment_dates_check
    check (
      shipped_at is null
      or delivered_at is null
      or delivered_at >= shipped_at
    )
);

create unique index fc_order_shipment_final_sample_round_key
  on public.fc_order_shipment (order_id, round_number)
  where shipment_type = 'final_sample';

create unique index fc_order_shipment_bulk_sequence_key
  on public.fc_order_shipment (order_id, sequence_number)
  where shipment_type = 'bulk_order';

create index fc_order_shipment_customer_order_idx
  on public.fc_order_shipment (customer_id, order_id, updated_at desc);

comment on table public.fc_order_shipment is
  'Repeatable Final Sample and bulk order shipment records shown to customers';

create function public.set_fc_order_shipment_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger set_fc_order_shipment_updated_at
before update on public.fc_order_shipment
for each row
execute function public.set_fc_order_shipment_updated_at();

insert into public.fc_order_shipment (
  order_id,
  customer_id,
  shipment_type,
  sequence_number,
  quantity,
  carrier,
  tracking_number,
  shipped_at,
  delivered_at
)
select
  fulfillment.order_id,
  fulfillment.customer_id,
  'bulk_order',
  1,
  customer_order.quantity,
  fulfillment.carrier,
  fulfillment.tracking_number,
  coalesce(fulfillment.shipped_at, fulfillment.updated_at),
  fulfillment.delivered_at
from public.fc_order_fulfillment as fulfillment
join public."order" as customer_order
  on customer_order.id = fulfillment.order_id
  and customer_order.customer_id = fulfillment.customer_id
where fulfillment.tracking_number is not null
  and length(trim(fulfillment.tracking_number)) > 0
on conflict do nothing;

alter table public.fc_order_shipment enable row level security;

revoke all on table public.fc_order_shipment from public, anon, authenticated;
revoke all on sequence public.fc_order_shipment_id_seq from public, anon, authenticated;
revoke all on function public.set_fc_order_shipment_updated_at() from public;

grant select, insert, update, delete
  on table public.fc_order_shipment
  to service_role;
grant usage, select
  on sequence public.fc_order_shipment_id_seq
  to service_role;
