-- Orders & Delivery: FC fulfillment state and customer-visible activity.
-- Existing order/payment rows remain the source of truth for commercial data.

alter table public."order"
  add constraint order_id_customer_id_key unique (id, customer_id);

create table public.fc_order_fulfillment (
  id bigint generated by default as identity primary key,
  order_id bigint not null unique,
  customer_id bigint not null,
  status text not null,
  last_active_status text,

  action_required boolean not null default false,
  next_action_title text,
  next_action_description text,
  next_action_due_at timestamptz,

  carrier text,
  tracking_number text,
  tracking_url text,
  shipped_at timestamptz,
  estimated_delivery_start timestamptz,
  estimated_delivery_end timestamptz,
  delivered_at timestamptz,

  distribution_status text,
  distribution_method text,
  planned_quantity integer,
  distributed_quantity integer not null default 0,
  distribution_start_at timestamptz,
  distribution_notes text,

  hold_reason text,
  cancel_reason text,
  invoice_number text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint fc_order_fulfillment_order_customer_fkey
    foreign key (order_id, customer_id)
    references public."order" (id, customer_id)
    on delete cascade,
  constraint fc_order_fulfillment_customer_id_fkey
    foreign key (customer_id)
    references public.customer (id)
    on delete cascade,
  constraint fc_order_fulfillment_order_customer_key
    unique (order_id, customer_id),
  constraint fc_order_fulfillment_status_check
    check (
      status = any (
        array[
          'payment_pending',
          'order_confirmed',
          'awaiting_brand_inputs',
          'design_in_progress',
          'awaiting_design_approval',
          'design_approved',
          'production',
          'quality_check',
          'ready_to_ship',
          'shipped',
          'delivered',
          'distribution_planning',
          'distributing',
          'completed',
          'on_hold',
          'cancelled'
        ]::text[]
      )
    ),
  constraint fc_order_fulfillment_last_active_status_check
    check (
      last_active_status is null
      or last_active_status = any (
        array[
          'payment_pending',
          'order_confirmed',
          'awaiting_brand_inputs',
          'design_in_progress',
          'awaiting_design_approval',
          'design_approved',
          'production',
          'quality_check',
          'ready_to_ship',
          'shipped',
          'delivered',
          'distribution_planning',
          'distributing',
          'completed'
        ]::text[]
      )
    ),
  constraint fc_order_fulfillment_action_check
    check (
      not action_required
      or length(trim(coalesce(next_action_title, ''))) > 0
    ),
  constraint fc_order_fulfillment_tracking_url_check
    check (tracking_url is null or tracking_url ~* '^https://'),
  constraint fc_order_fulfillment_estimated_delivery_check
    check (
      estimated_delivery_start is null
      or estimated_delivery_end is null
      or estimated_delivery_end >= estimated_delivery_start
    ),
  constraint fc_order_fulfillment_delivery_dates_check
    check (
      shipped_at is null
      or delivered_at is null
      or delivered_at >= shipped_at
    ),
  constraint fc_order_fulfillment_distribution_status_check
    check (
      distribution_status is null
      or distribution_status = any (
        array[
          'not_planned',
          'planning',
          'ready',
          'distributing',
          'completed'
        ]::text[]
      )
    ),
  constraint fc_order_fulfillment_distribution_method_check
    check (
      distribution_method is null
      or distribution_method = any (
        array[
          'brand_warehouse',
          'third_party_logistics',
          'selected_shopify_orders',
          'manual_distribution',
          'not_decided'
        ]::text[]
      )
    ),
  constraint fc_order_fulfillment_planned_quantity_check
    check (planned_quantity is null or planned_quantity >= 0),
  constraint fc_order_fulfillment_distributed_quantity_check
    check (distributed_quantity >= 0),
  constraint fc_order_fulfillment_distribution_balance_check
    check (
      planned_quantity is null
      or distributed_quantity <= planned_quantity
    ),
  constraint fc_order_fulfillment_hold_reason_check
    check (
      status <> 'on_hold'
      or length(trim(coalesce(hold_reason, ''))) > 0
    ),
  constraint fc_order_fulfillment_cancel_reason_check
    check (
      status <> 'cancelled'
      or length(trim(coalesce(cancel_reason, ''))) > 0
    )
);

comment on table public.fc_order_fulfillment is
  'Customer-visible fulfillment, shipment, action and distribution state for FC orders';
comment on column public.fc_order_fulfillment.last_active_status is
  'Last non-hold/non-cancelled status, used to preserve progress while an order is on hold';
comment on column public.fc_order_fulfillment.invoice_number is
  'Optional customer-facing invoice identifier; payment_no is not used as an invoice number';

create table public.fc_order_fulfillment_event (
  id bigint generated by default as identity primary key,
  order_id bigint not null,
  customer_id bigint not null,
  event_type text not null,
  title text not null,
  description text,
  actor_type text,
  occurred_at timestamptz not null,
  created_at timestamptz not null default now(),

  constraint fc_order_fulfillment_event_order_customer_fkey
    foreign key (order_id, customer_id)
    references public.fc_order_fulfillment (order_id, customer_id)
    on delete cascade,
  constraint fc_order_fulfillment_event_customer_id_fkey
    foreign key (customer_id)
    references public.customer (id)
    on delete cascade,
  constraint fc_order_fulfillment_event_type_check
    check (length(trim(event_type)) > 0),
  constraint fc_order_fulfillment_event_title_check
    check (length(trim(title)) > 0),
  constraint fc_order_fulfillment_event_actor_type_check
    check (
      actor_type is null
      or actor_type = any (array['brand', 'fc', 'system']::text[])
    )
);

comment on table public.fc_order_fulfillment_event is
  'Customer-visible order fulfillment timeline events';

create index fc_order_fulfillment_customer_status_updated_idx
  on public.fc_order_fulfillment (customer_id, status, updated_at desc);

create index fc_order_fulfillment_event_order_occurred_idx
  on public.fc_order_fulfillment_event (
    customer_id,
    order_id,
    occurred_at desc
  );

create function public.set_fc_order_fulfillment_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger set_fc_order_fulfillment_updated_at
before update on public.fc_order_fulfillment
for each row
execute function public.set_fc_order_fulfillment_updated_at();

alter table public.fc_order_fulfillment enable row level security;
alter table public.fc_order_fulfillment_event enable row level security;

revoke all on table public.fc_order_fulfillment from public, anon, authenticated;
revoke all on table public.fc_order_fulfillment_event from public, anon, authenticated;
revoke all on sequence public.fc_order_fulfillment_id_seq from public, anon, authenticated;
revoke all on sequence public.fc_order_fulfillment_event_id_seq from public, anon, authenticated;
revoke all on function public.set_fc_order_fulfillment_updated_at() from public;

grant select, insert, update, delete
  on table public.fc_order_fulfillment
  to service_role;
grant select, insert, update, delete
  on table public.fc_order_fulfillment_event
  to service_role;
grant usage, select
  on sequence public.fc_order_fulfillment_id_seq
  to service_role;
grant usage, select
  on sequence public.fc_order_fulfillment_event_id_seq
  to service_role;
