-- FC Reorder foundation: Amazon context and versioned products.
-- Existing FC orders remain the source of truth for ordered quantity.

create extension if not exists pgcrypto;

create table if not exists public.reorder_brand_settings (
  customer_id bigint primary key references public.customer(id) on delete cascade,
  brand_display_name text not null,
  brand_logo_url text,
  attribution_ready boolean not null default false,
  brb_ready boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reorder_brand_settings_name_check
    check (char_length(btrim(brand_display_name)) between 1 and 120)
);

create table if not exists public.reorder_selling_account (
  id uuid primary key default gen_random_uuid(),
  customer_id bigint not null references public.customer(id) on delete cascade,
  label text not null,
  marketplace_code text not null,
  marketplace_domain text not null,
  marketplace_id text,
  seller_id text not null,
  storefront_url text not null,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reorder_selling_account_label_check
    check (char_length(btrim(label)) between 1 and 120),
  constraint reorder_selling_account_marketplace_code_check
    check (marketplace_code ~ '^[A-Z0-9_-]{2,24}$'),
  constraint reorder_selling_account_domain_check
    check (marketplace_domain ~ '^[a-z0-9.-]+$'),
  constraint reorder_selling_account_seller_id_check
    check (seller_id ~ '^[A-Z0-9]{5,32}$'),
  constraint reorder_selling_account_status_check
    check (status in ('active', 'inactive')),
  unique (customer_id, marketplace_code, seller_id),
  unique (id, customer_id)
);

create table if not exists public.reorder_product_version (
  id uuid primary key default gen_random_uuid(),
  product_key uuid not null default gen_random_uuid(),
  version_number integer not null default 1,
  customer_id bigint not null references public.customer(id) on delete cascade,
  selling_account_id uuid not null,
  product_name text not null,
  variant_size text,
  image_url text,
  asin text not null,
  amazon_seller_pdp_url text not null,
  attribution_url text not null,
  seller_offer_available boolean not null default false,
  status text not null default 'draft',
  is_current boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reorder_product_version_account_fkey
    foreign key (selling_account_id, customer_id)
    references public.reorder_selling_account(id, customer_id),
  constraint reorder_product_version_name_check
    check (char_length(btrim(product_name)) between 1 and 200),
  constraint reorder_product_version_asin_check
    check (asin ~ '^[A-Z0-9]{10}$'),
  constraint reorder_product_version_number_check
    check (version_number > 0),
  constraint reorder_product_version_status_check
    check (status in ('draft', 'ready', 'active', 'retired')),
  unique (customer_id, product_key, version_number)
);

create unique index if not exists reorder_product_one_current_version_idx
  on public.reorder_product_version (customer_id, product_key)
  where is_current;

create index if not exists reorder_product_customer_updated_idx
  on public.reorder_product_version (customer_id, updated_at desc)
  where is_current;

create table if not exists public.reorder_audit_log (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customer(id) on delete cascade,
  actor_auth_user_id uuid,
  entity_type text not null,
  entity_id text not null,
  action text not null,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz not null default now()
);

create index if not exists reorder_audit_customer_created_idx
  on public.reorder_audit_log (customer_id, created_at desc);

create or replace function public.set_reorder_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_reorder_brand_settings_updated_at
  on public.reorder_brand_settings;
create trigger set_reorder_brand_settings_updated_at
before update on public.reorder_brand_settings
for each row execute function public.set_reorder_updated_at();

drop trigger if exists set_reorder_selling_account_updated_at
  on public.reorder_selling_account;
create trigger set_reorder_selling_account_updated_at
before update on public.reorder_selling_account
for each row execute function public.set_reorder_updated_at();

drop trigger if exists set_reorder_product_version_updated_at
  on public.reorder_product_version;
create trigger set_reorder_product_version_updated_at
before update on public.reorder_product_version
for each row execute function public.set_reorder_updated_at();

alter table public.reorder_brand_settings enable row level security;
alter table public.reorder_selling_account enable row level security;
alter table public.reorder_product_version enable row level security;
alter table public.reorder_audit_log enable row level security;

revoke all on table public.reorder_brand_settings from public, anon, authenticated;
revoke all on table public.reorder_selling_account from public, anon, authenticated;
revoke all on table public.reorder_product_version from public, anon, authenticated;
revoke all on table public.reorder_audit_log from public, anon, authenticated;
revoke all on sequence public.reorder_audit_log_id_seq from public, anon, authenticated;
revoke all on function public.set_reorder_updated_at() from public;

grant select, insert, update, delete on table public.reorder_brand_settings to service_role;
grant select, insert, update, delete on table public.reorder_selling_account to service_role;
grant select, insert, update, delete on table public.reorder_product_version to service_role;
grant select, insert on table public.reorder_audit_log to service_role;
grant usage, select on sequence public.reorder_audit_log_id_seq to service_role;
grant execute on function public.set_reorder_updated_at() to service_role;
