-- Normalized FC Reorder source manifests, coverage, errors, and facts.

create table if not exists public.reorder_data_source (
  id uuid primary key default gen_random_uuid(),
  customer_id bigint not null references public.customer(id) on delete cascade,
  source_kind text not null,
  coverage_status text not null default 'missing',
  freshness_status text not null default 'unknown',
  granularity text,
  covered_from timestamptz,
  covered_to timestamptz,
  covered_product_version_ids uuid[] not null default '{}',
  covered_batch_ids uuid[] not null default '{}',
  latest_import_id uuid,
  last_updated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reorder_data_source_kind_check check (source_kind in ('fulfillment','delivery','fc_event','order_attribution')),
  constraint reorder_data_source_coverage_check check (coverage_status in ('connected','partial','missing','degraded')),
  constraint reorder_data_source_freshness_check check (freshness_status in ('current','stale','unknown')),
  constraint reorder_data_source_granularity_check check (granularity is null or granularity in ('aggregate','batch','fc_id')),
  constraint reorder_data_source_range_check check (covered_from is null or covered_to is null or covered_to >= covered_from),
  unique (customer_id, source_kind),
  unique (id, customer_id),
  unique (id, customer_id, source_kind)
);

create table if not exists public.reorder_data_import (
  id uuid primary key default gen_random_uuid(),
  customer_id bigint not null,
  data_source_id uuid not null,
  source_kind text not null,
  import_mode text not null default 'import',
  status text not null default 'previewed',
  source_file_name text not null,
  source_file_sha256 text not null,
  granularity text,
  total_rows integer not null default 0,
  accepted_rows integer not null default 0,
  rejected_rows integer not null default 0,
  covered_from timestamptz,
  covered_to timestamptz,
  covered_product_version_ids uuid[] not null default '{}',
  covered_batch_ids uuid[] not null default '{}',
  replacement_scope jsonb,
  replacement_reason text,
  replaces_import_id uuid,
  committed_at timestamptz,
  created_by uuid,
  created_at timestamptz not null default now(),
  constraint reorder_data_import_source_fkey foreign key (data_source_id, customer_id, source_kind)
    references public.reorder_data_source(id, customer_id, source_kind) on delete cascade,
  constraint reorder_data_import_kind_check check (source_kind in ('fulfillment','delivery','order_attribution')),
  constraint reorder_data_import_mode_check check (import_mode in ('import','replace')),
  constraint reorder_data_import_status_check check (status in ('previewed','committed','failed','superseded')),
  constraint reorder_data_import_granularity_check check (granularity is null or granularity in ('aggregate','batch','fc_id')),
  constraint reorder_data_import_counts_check check (total_rows >= 0 and accepted_rows >= 0 and rejected_rows >= 0 and accepted_rows + rejected_rows <= total_rows),
  constraint reorder_data_import_replace_check check ((import_mode = 'replace' and replacement_scope is not null and char_length(btrim(coalesce(replacement_reason,''))) > 0) or (import_mode = 'import' and replacement_scope is null and replacement_reason is null)),
  unique (customer_id, source_kind, source_file_sha256),
  unique (id, customer_id),
  unique (id, customer_id, source_kind)
);

alter table public.reorder_data_source
  add constraint reorder_data_source_latest_import_fkey foreign key (latest_import_id, customer_id)
  references public.reorder_data_import(id, customer_id);

alter table public.reorder_data_import
  add constraint reorder_data_import_replaces_fkey foreign key (replaces_import_id, customer_id)
  references public.reorder_data_import(id, customer_id);

create table if not exists public.reorder_data_import_error (
  id bigint generated by default as identity primary key,
  import_id uuid not null,
  customer_id bigint not null references public.customer(id) on delete cascade,
  row_number integer not null,
  field_name text not null,
  error_code text not null,
  safe_message text not null,
  created_at timestamptz not null default now(),
  constraint reorder_data_import_error_import_fkey foreign key (import_id, customer_id)
    references public.reorder_data_import(id, customer_id) on delete cascade,
  constraint reorder_data_import_error_row_check check (row_number > 0)
);

create table if not exists public.reorder_source_fact (
  id bigint generated by default as identity primary key,
  import_id uuid not null,
  customer_id bigint not null references public.customer(id) on delete cascade,
  source_kind text not null,
  external_key text not null,
  occurred_at timestamptz not null,
  granularity text not null,
  product_version_id uuid,
  batch_id uuid,
  fc_id text,
  quantity integer not null,
  anonymous_order_key text,
  attribution_key text,
  order_status text,
  order_type text,
  created_at timestamptz not null default now(),
  constraint reorder_source_fact_import_fkey foreign key (import_id, customer_id, source_kind)
    references public.reorder_data_import(id, customer_id, source_kind) on delete cascade,
  constraint reorder_source_fact_product_fkey foreign key (product_version_id, customer_id)
    references public.reorder_product_version(id, customer_id),
  constraint reorder_source_fact_batch_fkey foreign key (batch_id, customer_id)
    references public.reorder_fc_batch(id, customer_id),
  constraint reorder_source_fact_fc_fkey foreign key (fc_id, customer_id)
    references public.reorder_fc_unit(fc_id, customer_id),
  constraint reorder_source_fact_kind_check check (source_kind in ('fulfillment','delivery','order_attribution')),
  constraint reorder_source_fact_granularity_check check (granularity in ('aggregate','batch','fc_id')),
  constraint reorder_source_fact_quantity_check check (quantity >= 0),
  constraint reorder_source_fact_scope_check check ((granularity <> 'batch' or batch_id is not null) and (granularity <> 'fc_id' or fc_id is not null)),
  unique (customer_id, source_kind, external_key)
);

create index if not exists reorder_data_import_customer_created_idx on public.reorder_data_import(customer_id, source_kind, created_at desc);
create index if not exists reorder_data_import_error_lookup_idx on public.reorder_data_import_error(customer_id, import_id, row_number);
create index if not exists reorder_source_fact_metric_idx on public.reorder_source_fact(customer_id, source_kind, occurred_at, product_version_id, batch_id);
create index if not exists reorder_source_fact_fc_idx on public.reorder_source_fact(customer_id, fc_id, occurred_at) where fc_id is not null;

create trigger set_reorder_data_source_updated_at before update on public.reorder_data_source
for each row execute function public.set_reorder_updated_at();

alter table public.reorder_data_source enable row level security;
alter table public.reorder_data_import enable row level security;
alter table public.reorder_data_import_error enable row level security;
alter table public.reorder_source_fact enable row level security;
revoke all on public.reorder_data_source, public.reorder_data_import, public.reorder_data_import_error, public.reorder_source_fact from public, anon, authenticated;
grant select, insert, update, delete on public.reorder_data_source, public.reorder_data_import, public.reorder_data_import_error, public.reorder_source_fact to service_role;
