-- FC Reorder physical lifecycle.
-- public."order" remains the immutable source of Total Ordered Quantity.

create table if not exists public.reorder_fc_order_state (
  order_id bigint primary key,
  customer_id bigint not null,
  allocation_status text not null default 'ready',
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reorder_fc_order_state_order_customer_fkey
    foreign key (order_id, customer_id)
    references public."order" (id, customer_id)
    on delete cascade,
  constraint reorder_fc_order_state_status_check
    check (allocation_status in ('ready', 'draft', 'submitted')),
  constraint reorder_fc_order_state_submitted_check
    check (
      (allocation_status = 'submitted' and submitted_at is not null)
      or (allocation_status <> 'submitted' and submitted_at is null)
    ),
  unique (order_id, customer_id)
);

create table if not exists public.reorder_product_allocation (
  id uuid primary key default gen_random_uuid(),
  order_id bigint not null,
  customer_id bigint not null,
  product_version_id uuid not null,
  quantity integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reorder_product_allocation_order_fkey
    foreign key (order_id, customer_id)
    references public."order" (id, customer_id)
    on delete cascade,
  constraint reorder_product_allocation_product_fkey
    foreign key (product_version_id, customer_id)
    references public.reorder_product_version (id, customer_id),
  constraint reorder_product_allocation_quantity_check check (quantity > 0),
  unique (order_id, product_version_id),
  unique (id, order_id, customer_id, product_version_id)
);

create table if not exists public.reorder_fc_batch (
  id uuid primary key default gen_random_uuid(),
  batch_code text not null,
  order_id bigint not null,
  customer_id bigint not null,
  product_allocation_id uuid not null,
  product_version_id uuid not null,
  label text not null,
  quantity integer not null,
  fc_id_count integer not null default 0,
  fc_id_start text,
  fc_id_end text,
  production_status text not null default 'ordered',
  qa_status text,
  nfc_write_status text,
  shipment_status text not null default 'ready_to_ship',
  ship_to text,
  quantity_shipped integer not null default 0,
  shipped_at timestamptz,
  carrier text,
  tracking_reference text,
  delivered_to_fulfillment_at timestamptz,
  activation_status text not null default 'draft',
  scheduled_activation_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reorder_fc_batch_allocation_fkey
    foreign key (
      product_allocation_id,
      order_id,
      customer_id,
      product_version_id
    ) references public.reorder_product_allocation (
      id,
      order_id,
      customer_id,
      product_version_id
    ),
  constraint reorder_fc_batch_code_check
    check (char_length(btrim(batch_code)) between 1 and 80),
  constraint reorder_fc_batch_label_check
    check (char_length(btrim(label)) between 1 and 200),
  constraint reorder_fc_batch_quantity_check check (quantity > 0),
  constraint reorder_fc_batch_fc_id_count_check
    check (fc_id_count between 0 and quantity),
  constraint reorder_fc_batch_quantity_shipped_check
    check (quantity_shipped between 0 and quantity),
  constraint reorder_fc_batch_production_status_check
    check (production_status in (
      'ordered', 'in_production', 'nfc_written', 'qa', 'ready', 'shipped',
      'on_hold', 'failed_qa'
    )),
  constraint reorder_fc_batch_shipment_status_check
    check (shipment_status in (
      'ready_to_ship', 'in_transit', 'delivered_to_fulfillment'
    )),
  constraint reorder_fc_batch_activation_status_check
    check (activation_status in ('draft', 'scheduled', 'active', 'paused', 'retired')),
  constraint reorder_fc_batch_activation_schedule_check
    check (
      (activation_status = 'scheduled' and scheduled_activation_at is not null)
      or activation_status <> 'scheduled'
    ),
  unique (customer_id, batch_code),
  unique (id, customer_id)
);

create table if not exists public.reorder_fc_batch_event (
  id bigint generated by default as identity primary key,
  batch_id uuid not null,
  customer_id bigint not null,
  event_type text not null,
  title text not null,
  description text,
  actor_type text,
  occurred_at timestamptz not null,
  created_at timestamptz not null default now(),
  constraint reorder_fc_batch_event_batch_fkey
    foreign key (batch_id, customer_id)
    references public.reorder_fc_batch (id, customer_id)
    on delete cascade,
  constraint reorder_fc_batch_event_type_check
    check (char_length(btrim(event_type)) between 1 and 80),
  constraint reorder_fc_batch_event_title_check
    check (char_length(btrim(title)) between 1 and 200),
  constraint reorder_fc_batch_event_actor_check
    check (actor_type is null or actor_type in ('fc_ops', 'system', 'brand'))
);

create index if not exists reorder_allocation_customer_order_idx
  on public.reorder_product_allocation (customer_id, order_id);
create index if not exists reorder_allocation_product_idx
  on public.reorder_product_allocation (customer_id, product_version_id);
create index if not exists reorder_batch_customer_order_idx
  on public.reorder_fc_batch (customer_id, order_id, created_at desc);
create index if not exists reorder_batch_product_idx
  on public.reorder_fc_batch (customer_id, product_version_id, created_at desc);
create index if not exists reorder_batch_event_timeline_idx
  on public.reorder_fc_batch_event (customer_id, batch_id, occurred_at desc);

create trigger set_reorder_fc_order_state_updated_at
before update on public.reorder_fc_order_state
for each row execute function public.set_reorder_updated_at();

create trigger set_reorder_product_allocation_updated_at
before update on public.reorder_product_allocation
for each row execute function public.set_reorder_updated_at();

create trigger set_reorder_fc_batch_updated_at
before update on public.reorder_fc_batch
for each row execute function public.set_reorder_updated_at();

create or replace function public.validate_reorder_fc_batch()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  v_allocation_quantity integer;
  v_existing_quantity bigint;
  v_allocation_status text;
begin
  select allocation.quantity, state.allocation_status
  into v_allocation_quantity, v_allocation_status
  from public.reorder_product_allocation allocation
  join public.reorder_fc_order_state state
    on state.order_id = allocation.order_id
    and state.customer_id = allocation.customer_id
  where allocation.id = new.product_allocation_id
    and allocation.order_id = new.order_id
    and allocation.customer_id = new.customer_id
    and allocation.product_version_id = new.product_version_id
  for update of allocation;

  if not found or v_allocation_status <> 'submitted' then
    raise exception 'Batch requires a submitted Product Allocation';
  end if;

  select coalesce(sum(quantity), 0) into v_existing_quantity
  from public.reorder_fc_batch
  where product_allocation_id = new.product_allocation_id
    and id <> new.id;
  if v_existing_quantity + new.quantity > v_allocation_quantity then
    raise exception 'Batch Quantity cannot exceed Product Allocation Quantity';
  end if;
  return new;
end;
$$;

create trigger validate_reorder_fc_batch_before_write
before insert or update of product_allocation_id, order_id, customer_id,
  product_version_id, quantity
on public.reorder_fc_batch
for each row execute function public.validate_reorder_fc_batch();

create or replace function public.save_reorder_product_allocations(
  p_customer_id bigint,
  p_order_id bigint,
  p_allocations jsonb
)
returns setof public.reorder_product_allocation
language plpgsql
security definer
set search_path = public
as $$
declare
  v_total integer;
  v_allocated bigint;
  v_status text;
  v_count integer;
  v_distinct_count integer;
begin
  if jsonb_typeof(p_allocations) <> 'array' then
    raise exception 'Allocations must be an array';
  end if;

  select quantity into v_total
  from public."order"
  where id = p_order_id and customer_id = p_customer_id
  for update;
  if not found then raise exception 'FC Order not found'; end if;

  insert into public.reorder_fc_order_state (order_id, customer_id)
  values (p_order_id, p_customer_id)
  on conflict (order_id) do nothing;

  select allocation_status into v_status
  from public.reorder_fc_order_state
  where order_id = p_order_id and customer_id = p_customer_id
  for update;
  if v_status = 'submitted' then
    raise exception 'Submitted allocations are locked';
  end if;

  select
    count(*),
    count(distinct (item->>'productVersionId')),
    coalesce(sum((item->>'quantity')::bigint), 0)
  into v_count, v_distinct_count, v_allocated
  from jsonb_array_elements(p_allocations) item;

  if v_count <> v_distinct_count then
    raise exception 'Each Product Version may appear only once';
  end if;
  if exists (
    select 1 from jsonb_array_elements(p_allocations) item
    where coalesce(item->>'productVersionId', '') = ''
      or coalesce(item->>'quantity', '') !~ '^[1-9][0-9]*$'
  ) then
    raise exception 'Each allocation requires a Product Version and positive quantity';
  end if;
  if v_allocated > v_total then
    raise exception 'Allocated Quantity cannot exceed Total Ordered Quantity';
  end if;
  if exists (
    select 1
    from jsonb_array_elements(p_allocations) item
    left join public.reorder_product_version product
      on product.id = (item->>'productVersionId')::uuid
      and product.customer_id = p_customer_id
      and product.is_current
      and product.status in ('ready', 'active')
      and product.image_url is not null
    where product.id is null
  ) then
    raise exception 'Select a current, production-ready Product Version';
  end if;

  delete from public.reorder_product_allocation
  where order_id = p_order_id and customer_id = p_customer_id;

  insert into public.reorder_product_allocation (
    order_id, customer_id, product_version_id, quantity
  )
  select
    p_order_id,
    p_customer_id,
    (item->>'productVersionId')::uuid,
    (item->>'quantity')::integer
  from jsonb_array_elements(p_allocations) item;

  update public.reorder_fc_order_state
  set allocation_status = case when v_count = 0 then 'ready' else 'draft' end,
      submitted_at = null
  where order_id = p_order_id and customer_id = p_customer_id;

  insert into public.reorder_audit_log (
    customer_id, entity_type, entity_id, action, after_data
  ) values (
    p_customer_id, 'fc_order', p_order_id::text, 'save_allocation', p_allocations
  );

  return query
  select * from public.reorder_product_allocation
  where order_id = p_order_id and customer_id = p_customer_id
  order by created_at;
end;
$$;

create or replace function public.submit_reorder_product_allocations(
  p_customer_id bigint,
  p_order_id bigint
)
returns public.reorder_fc_order_state
language plpgsql
security definer
set search_path = public
as $$
declare
  v_total integer;
  v_allocated bigint;
  v_result public.reorder_fc_order_state;
begin
  select quantity into v_total
  from public."order"
  where id = p_order_id and customer_id = p_customer_id
  for update;
  if not found then raise exception 'FC Order not found'; end if;

  select coalesce(sum(quantity), 0) into v_allocated
  from public.reorder_product_allocation
  where order_id = p_order_id and customer_id = p_customer_id;
  if v_allocated <> v_total then
    raise exception 'All magnets must be allocated before submission';
  end if;

  insert into public.reorder_fc_order_state (
    order_id, customer_id, allocation_status, submitted_at
  ) values (
    p_order_id, p_customer_id, 'submitted', now()
  )
  on conflict (order_id) do update
    set allocation_status = 'submitted', submitted_at = now()
  returning * into v_result;

  insert into public.reorder_audit_log (
    customer_id, entity_type, entity_id, action, after_data
  ) values (
    p_customer_id,
    'fc_order',
    p_order_id::text,
    'submit_allocation',
    jsonb_build_object('totalOrdered', v_total, 'allocated', v_allocated)
  );

  return v_result;
end;
$$;

create or replace function public.transition_reorder_batch_activation(
  p_customer_id bigint,
  p_batch_id uuid,
  p_from_status text,
  p_to_status text,
  p_scheduled_activation_at timestamptz default null
)
returns public.reorder_fc_batch
language plpgsql
security definer
set search_path = public
as $$
declare
  v_result public.reorder_fc_batch;
  v_production_status text;
  v_product_status text;
  v_product_image text;
begin
  if not (
    (p_from_status = 'draft' and p_to_status in ('scheduled', 'active', 'retired'))
    or (p_from_status = 'scheduled' and p_to_status in ('draft', 'active', 'paused', 'retired'))
    or (p_from_status = 'active' and p_to_status in ('paused', 'retired'))
    or (p_from_status = 'paused' and p_to_status in ('scheduled', 'active', 'retired'))
  ) then
    raise exception 'Invalid Batch activation transition';
  end if;
  if p_to_status = 'scheduled'
    and (p_scheduled_activation_at is null or p_scheduled_activation_at <= now()) then
    raise exception 'Scheduled activation must be a future date and time';
  end if;

  select batch.production_status, product.status, product.image_url
  into v_production_status, v_product_status, v_product_image
  from public.reorder_fc_batch batch
  join public.reorder_product_version product
    on product.id = batch.product_version_id
    and product.customer_id = batch.customer_id
  where batch.id = p_batch_id
    and batch.customer_id = p_customer_id
    and batch.activation_status = p_from_status
  for update of batch;
  if not found then raise exception 'Batch activation changed; refresh and try again'; end if;
  if p_to_status in ('scheduled', 'active')
    and (v_product_status not in ('ready', 'active') or v_product_image is null) then
    raise exception 'Complete the Product Version before activation';
  end if;
  if p_to_status = 'active' and v_production_status not in ('ready', 'shipped') then
    raise exception 'Batch Production must be Ready before activation';
  end if;

  update public.reorder_fc_batch
  set activation_status = p_to_status,
      scheduled_activation_at = case
        when p_to_status = 'scheduled' then p_scheduled_activation_at
        else null
      end
  where id = p_batch_id
    and customer_id = p_customer_id
    and activation_status = p_from_status
  returning * into v_result;
  if not found then raise exception 'Batch activation changed; refresh and try again'; end if;

  insert into public.reorder_audit_log (
    customer_id, entity_type, entity_id, action, before_data, after_data
  ) values (
    p_customer_id,
    'fc_batch',
    p_batch_id::text,
    'activation_transition',
    jsonb_build_object('activationStatus', p_from_status),
    jsonb_build_object(
      'activationStatus', p_to_status,
      'scheduledActivationAt', p_scheduled_activation_at
    )
  );
  return v_result;
end;
$$;

alter table public.reorder_fc_order_state enable row level security;
alter table public.reorder_product_allocation enable row level security;
alter table public.reorder_fc_batch enable row level security;
alter table public.reorder_fc_batch_event enable row level security;

revoke all on table public.reorder_fc_order_state from public, anon, authenticated;
revoke all on table public.reorder_product_allocation from public, anon, authenticated;
revoke all on table public.reorder_fc_batch from public, anon, authenticated;
revoke all on table public.reorder_fc_batch_event from public, anon, authenticated;
revoke all on sequence public.reorder_fc_batch_event_id_seq from public, anon, authenticated;
revoke all on function public.save_reorder_product_allocations(bigint, bigint, jsonb) from public;
revoke all on function public.submit_reorder_product_allocations(bigint, bigint) from public;
revoke all on function public.transition_reorder_batch_activation(bigint, uuid, text, text, timestamptz) from public;
revoke all on function public.validate_reorder_fc_batch() from public;

grant select, insert, update, delete on table public.reorder_fc_order_state to service_role;
grant select, insert, update, delete on table public.reorder_product_allocation to service_role;
grant select, insert, update, delete on table public.reorder_fc_batch to service_role;
grant select, insert, update, delete on table public.reorder_fc_batch_event to service_role;
grant usage, select on sequence public.reorder_fc_batch_event_id_seq to service_role;
grant execute on function public.save_reorder_product_allocations(bigint, bigint, jsonb) to service_role;
grant execute on function public.submit_reorder_product_allocations(bigint, bigint) to service_role;
grant execute on function public.transition_reorder_batch_activation(bigint, uuid, text, text, timestamptz) to service_role;
grant execute on function public.validate_reorder_fc_batch() to service_role;
